In [1]:
import numpy as np
import torch
from torch.utils import data
from d2l import torch as d2l

In [2]:
true_w = torch.tensor([2,-3.4])
true_b = 4.2
features,labels = d2l.synthetic_data(true_w,true_b,1000)

In [3]:
def load_array(data_arrays,batch_size,is_train=True):#@save
    dataset = data.TensorDataset(*data_arrays)  # 内置的分割数据集函数
    return data.DataLoader(dataset,batch_size,shuffle=is_train)

In [4]:
batch_size = 10
data_iter = load_array((features,labels),batch_size)

In [5]:
next(iter(data_iter))

[tensor([[-0.3364,  1.8098],
         [-1.3303,  0.9916],
         [ 0.6994,  1.1505],
         [-0.5102, -0.1088],
         [ 0.0317, -0.4384],
         [ 1.7379,  0.8878],
         [ 0.5365, -0.6603],
         [-0.2006, -1.4531],
         [-1.1343, -1.0646],
         [-0.3188,  0.4989]]),
 tensor([[-2.6362],
         [-1.8219],
         [ 1.6846],
         [ 3.5523],
         [ 5.7458],
         [ 4.6635],
         [ 7.5413],
         [ 8.7454],
         [ 5.5505],
         [ 1.8820]])]

In [6]:
from torch import nn
net = nn.Sequential(nn.Linear(2,1)) # 定义神经层连接 输入2 输出1 要和前面的训练参数对应

In [7]:
# 初始化参数  w b
net[0].weight.data.normal_(0,0.01)

tensor([[0.0086, 0.0096]])

In [8]:
net[0].bias.data.fill_(0)

tensor([0.])

In [9]:
loss = nn.MSELoss()  # 设置损失函数

In [10]:
trainer = torch.optim.SGD(net.parameters(),lr=0.03)  # 目前来看好像参数只有lr net.parameters() 自动包含参数

In [14]:
num_epochs = 3
for epoch in range(num_epochs):
    for X,y in data_iter:
        l = loss(net(X),y)
        trainer.zero_grad()
        l.backward()
        trainer.step()
    l = loss(net(features),labels)
    print(f'epoch {epoch + 1},loss {l:f}')

epoch 1,loss 0.000113
epoch 2,loss 0.000113
epoch 3,loss 0.000113


In [15]:
w = net[0].weight.data
b = net[0].bias.data
w,b

(tensor([[ 1.9996, -3.4005]]), tensor([4.1990]))

In [16]:
print(true_w - w,true_b - b)

tensor([[0.0004, 0.0005]]) tensor([0.0010])
