In [1]:
import torch

In [2]:
x = torch.arange(12)

In [5]:
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [6]:
x.shape

torch.Size([12])

In [7]:
x.numel()

12

In [8]:
x.reshape(3,4)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [9]:
torch.zeros(2,3,4)

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [3]:
torch.zeros((2, 3, 4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [11]:
torch.randn(3,4)  # 标准差为1 均值为0 的正态分布随机采样

tensor([[-0.6079,  0.5969, -0.3138,  1.4058],
        [-0.1539, -0.5957, -1.4733, -0.2099],
        [-1.8536, -1.0410,  2.4168,  0.7800]])

In [12]:
torch.tensor([[2,3,4],[3,4,5],[4,5,6]])

tensor([[2, 3, 4],
        [3, 4, 5],
        [4, 5, 6]])

In [13]:
# 张量运算为元素的各个运算

In [14]:
x = torch.randn(4,4)

In [15]:
torch.exp(x)

tensor([[7.2520, 0.1604, 2.8689, 1.3471],
        [1.5202, 0.3950, 0.7737, 0.5907],
        [0.1483, 1.0010, 1.4149, 9.6452],
        [0.7374, 3.1242, 3.0048, 0.3971]])

In [16]:
x

tensor([[ 1.9813e+00, -1.8301e+00,  1.0539e+00,  2.9793e-01],
        [ 4.1885e-01, -9.2887e-01, -2.5661e-01, -5.2639e-01],
        [-1.9085e+00,  1.0209e-03,  3.4709e-01,  2.2665e+00],
        [-3.0463e-01,  1.1392e+00,  1.1002e+00, -9.2351e-01]])

In [17]:
X = torch.arange(12,dtype=torch.float32)

In [18]:
x

tensor([[ 1.9813e+00, -1.8301e+00,  1.0539e+00,  2.9793e-01],
        [ 4.1885e-01, -9.2887e-01, -2.5661e-01, -5.2639e-01],
        [-1.9085e+00,  1.0209e-03,  3.4709e-01,  2.2665e+00],
        [-3.0463e-01,  1.1392e+00,  1.1002e+00, -9.2351e-01]])

In [19]:
X

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [20]:
X.reshape(3,4)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [21]:
x_ = X.reshape(3,4)

In [22]:
y_ = torch.tensor([[1,2,3,4],[2,3,4,5],[3,4,5,6]])

In [23]:
torch.cat((x_,y_),dim=0)  #在后面直接添加

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [ 1.,  2.,  3.,  4.],
        [ 2.,  3.,  4.,  5.],
        [ 3.,  4.,  5.,  6.]])

In [24]:
torch.cat((x_,y_),dim=1)  # 在侧面直接添加 

tensor([[ 0.,  1.,  2.,  3.,  1.,  2.,  3.,  4.],
        [ 4.,  5.,  6.,  7.,  2.,  3.,  4.,  5.],
        [ 8.,  9., 10., 11.,  3.,  4.,  5.,  6.]])

In [31]:
# z_ = torch.tensor([[2,3,4,],[3,4,5,]])  # 按照轴的不同要求形状符合

In [32]:
X.sum()

tensor(66.)

In [33]:
y_.sum()

tensor(42)

In [34]:
x.sum()

tensor(1.9273)

In [35]:
x_+y_

tensor([[ 1.,  3.,  5.,  7.],
        [ 6.,  8., 10., 12.],
        [11., 13., 15., 17.]])

In [55]:
a = torch.ones(3,3,1)

In [56]:
b = torch.ones(1,4)

In [57]:
a,b

(tensor([[[1.],
          [1.],
          [1.]],
 
         [[1.],
          [1.],
          [1.]],
 
         [[1.],
          [1.],
          [1.]]]),
 tensor([[1., 1., 1., 1.]]))

In [58]:
a.shape,b.shape

(torch.Size([3, 3, 1]), torch.Size([1, 4]))

In [59]:
a+b  # 广播机制有待寻味

tensor([[[2., 2., 2., 2.],
         [2., 2., 2., 2.],
         [2., 2., 2., 2.]],

        [[2., 2., 2., 2.],
         [2., 2., 2., 2.],
         [2., 2., 2., 2.]],

        [[2., 2., 2., 2.],
         [2., 2., 2., 2.],
         [2., 2., 2., 2.]]])

In [60]:
# 切片

In [61]:
# 节省内存

In [62]:
A = torch.zeros_like(a)  

In [74]:
A,id(A)

(tensor([[[0.],
          [0.],
          [0.]],
 
         [[0.],
          [0.],
          [0.]],
 
         [[0.],
          [0.],
          [0.]]]),
 2150446534144)

In [71]:
A[:] = A + 0;id(A)

2150446534144

In [78]:
before = id(A)

In [79]:
id(A)

2150446534144

In [80]:
A[:] = A + 1

In [81]:
id(A)

2150446534144

In [82]:
A

tensor([[[2.],
         [2.],
         [2.]],

        [[2.],
         [2.],
         [2.]],

        [[2.],
         [2.],
         [2.]]])

In [94]:
before == id(A)  # 内存指向问题

True

In [96]:
# 张量类型转变

In [97]:
X = A.numpy()

In [104]:
Y = A.clone().detach()  # 新用法

In [108]:
type(X,),type(Y,)

(numpy.ndarray, torch.Tensor)

**在运行结果下面shitf+b 打开markdown**

In [113]:
a = torch.tensor((1))

In [114]:
a, a.item(), float(a), int(a)

(tensor(1), 1, 1.0, 1)