In [1]:
import torch

In [5]:
x = torch.tensor([[1,2,3],[2,3,4],[3,4,5],[4,5,6]])

In [7]:
x.shape

torch.Size([4, 3])

In [10]:
x[1]

tensor([2, 3, 4])

In [13]:
x[:, 0]  # 直接使用切片表示

tensor([1, 2, 3, 4])

In [14]:
y = torch.arange(20).reshape(5,4)

In [16]:
y.T,y

(tensor([[ 0,  4,  8, 12, 16],
         [ 1,  5,  9, 13, 17],
         [ 2,  6, 10, 14, 18],
         [ 3,  7, 11, 15, 19]]),
 tensor([[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11],
         [12, 13, 14, 15],
         [16, 17, 18, 19]]))

In [20]:
B = torch.tensor([[1,2,1],[2,0,1],[1,1,3]])

In [21]:
B == B.T

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

In [22]:
#  张量的数据运算和矩阵的数据运算 结构一样

In [23]:
x = torch.arange(20)

In [25]:
x;x.sum()

tensor(190)

In [34]:
A = x.reshape(4,5)

In [35]:
A_sum_axis0 = A.sum(axis=0)  # 0代表行加

In [38]:
A_sum_axis0,A_sum_axis0.shape,A  # ,变成元组了

(tensor([30, 34, 38, 42, 46]),
 torch.Size([5]),
 tensor([[ 0,  1,  2,  3,  4],
         [ 5,  6,  7,  8,  9],
         [10, 11, 12, 13, 14],
         [15, 16, 17, 18, 19]]))

In [42]:
A_sum_axis1 = A.sum(axis=1)  # 1代表列加

In [43]:
A_sum_axis1,A_sum_axis1.shape,A 

(tensor([10, 35, 60, 85]),
 torch.Size([4]),
 tensor([[ 0,  1,  2,  3,  4],
         [ 5,  6,  7,  8,  9],
         [10, 11, 12, 13, 14],
         [15, 16, 17, 18, 19]]))

In [44]:
A_sum_axis0

tensor([30, 34, 38, 42, 46])

In [49]:
C = A.clone().detach()

In [50]:
C

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]])

In [52]:
# 非降维求和

In [60]:
sum_A = A.sum(axis=1,keepdim=True);sum_B = A.sum(axis=1)  # keepdim保持原来的维度不变

In [61]:
sum_A,sum_B

(tensor([[10],
         [35],
         [60],
         [85]]),
 tensor([10, 35, 60, 85]))

In [55]:
A

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]])

In [62]:
A/sum_A  # 广播机制 行归一化

tensor([[0.0000, 0.1000, 0.2000, 0.3000, 0.4000],
        [0.1429, 0.1714, 0.2000, 0.2286, 0.2571],
        [0.1667, 0.1833, 0.2000, 0.2167, 0.2333],
        [0.1765, 0.1882, 0.2000, 0.2118, 0.2235]])

In [64]:
A.cumsum(axis=0)  # 按行求和

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  7,  9, 11, 13],
        [15, 18, 21, 24, 27],
        [30, 34, 38, 42, 46]])

In [78]:
y = torch.ones(4,dtype=torch.float32);y

tensor([1., 1., 1., 1.])

In [94]:
torch.dot(x,y)  # 点积

tensor(6.)

In [96]:
x.reshape(-1,1)  # 变成列向量

tensor([[0.],
        [1.],
        [2.],
        [3.]])

In [87]:
x = torch.arange(4.0);x

tensor([0., 1., 2., 3.])

In [91]:
x.shape

torch.Size([4])

In [92]:
x.T.shape

torch.Size([4])

In [93]:
torch.sum(x*y)

tensor(6.)

In [97]:
# 矩阵和列常量的计算

In [104]:
x = 4  # 不是张量

In [105]:
x = torch.tensor([2,2,2,2])

In [106]:
x.shape

torch.Size([4])

In [107]:
A = torch.arange(20).reshape(5,4)

In [110]:
A.shape,A

(torch.Size([5, 4]),
 tensor([[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11],
         [12, 13, 14, 15],
         [16, 17, 18, 19]]))

In [111]:
torch.mv(A,x)  # 相乘运算mv

tensor([ 12,  44,  76, 108, 140])

In [115]:
B = A.reshape(4,5)  # 先变成一行 然后4，5

In [117]:
B

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]])

In [118]:
torch.mm(A,B)

tensor([[ 70,  76,  82,  88,  94],
        [190, 212, 234, 256, 278],
        [310, 348, 386, 424, 462],
        [430, 484, 538, 592, 646],
        [550, 620, 690, 760, 830]])

In [119]:
# 范数

In [127]:
B.shape

torch.Size([4, 5])

In [128]:
A.reshape(-1,1)  # 变成一行

tensor([[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11],
        [12],
        [13],
        [14],
        [15],
        [16],
        [17],
        [18],
        [19]])

In [129]:
u = torch.tensor([4,5])

In [132]:
u.shape

torch.Size([2])

In [134]:
A.reshape(-1)  # -1变成一维

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19])

In [142]:
A.reshape(-1)[4:6]

tensor([4, 5])

In [148]:
torch.norm(A.float())  # norm()只接收浮点数 L2范数

tensor(49.6991)

In [150]:
torch.abs(A).sum()  # L1范数

tensor(190)

In [151]:
len(A)

5

In [152]:
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

In [153]:
len(A[1])

4

In [154]:
A[1]

tensor([4, 5, 6, 7])

In [158]:
A[:,2].reshape(-1,1)

tensor([[ 2],
        [ 6],
        [10],
        [14],
        [18]])

In [160]:
K = torch.ones((2,3,4))

In [161]:
K

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [164]:
K.sum(axis=0),K.sum(axis=1),K.sum(axis=2)

(tensor([[2., 2., 2., 2.],
         [2., 2., 2., 2.],
         [2., 2., 2., 2.]]),
 tensor([[3., 3., 3., 3.],
         [3., 3., 3., 3.]]),
 tensor([[4., 4., 4.],
         [4., 4., 4.]]))

In [167]:
K.sum()

tensor(24.)

In [172]:
torch.linalg.norm(K)  # 更规范求范数的函数

tensor(4.8990)

In [173]:
torch.norm(K)

tensor(4.8990)