In [12]:
import torch
x = torch.arange(4.0)
x

tensor([0., 1., 2., 3.])

In [13]:
x.requires_grad_(True)  # 等价于 x=torch.arange(4.0,requires_grad=True)
x.grad

In [14]:
x

tensor([0., 1., 2., 3.], requires_grad=True)

In [38]:
y = 2*torch.dot(x,x)

In [26]:
y

tensor(28., grad_fn=<MulBackward0>)

In [27]:
y.backward()  # 计算储存在x.grad中 同时运行一遍计算图被释放
x.grad

tensor([ 0., 12., 24., 36.])

In [28]:
x.grad == 4*x

tensor([ True, False, False, False])

In [29]:
x.grad.zero_()

tensor([0., 0., 0., 0.])

In [71]:
y = x.sum()

In [72]:
y.backward()  #  反向传播

In [43]:
x.grad  # grad会累加 需要清空

tensor([ 1.,  9., 17., 25.])

In [54]:
x.grad.zero_()
y = x*x  # shift + ctrl + -分割代码块

In [45]:
y.sum().backward()
x.grad

tensor([0., 2., 4., 6.])

In [48]:
y

tensor([0., 1., 4., 9.], grad_fn=<MulBackward0>)

In [55]:
y.backward(gradient=torch.ones(len(x)))  # 传入梯度为1

In [51]:
x.grad

tensor([0., 2., 4., 6.])

In [52]:
torch.ones(len(x))

tensor([1., 1., 1., 1.])

In [56]:
x

tensor([0., 1., 2., 3.], requires_grad=True)

In [57]:
x.grad.zero_()

tensor([0., 0., 0., 0.])

In [58]:
y = x*x

In [59]:
u = y.detach()  # 把这个参数当成常量对待

In [60]:
u

tensor([0., 1., 4., 9.])

In [ ]:
z = u*x

In [68]:
z,z.sum()

(tensor([ 0.,  1.,  8., 27.], grad_fn=<MulBackward0>),
 tensor(36., grad_fn=<SumBackward0>))

In [62]:
z.sum().backward()

In [63]:
x.grad == u

tensor([True, True, True, True])

In [64]:
x.grad.zero_()

tensor([0., 0., 0., 0.])

In [65]:
y.sum().backward()

In [66]:
x.grad == 2 * x

tensor([True, True, True, True])

In [73]:
def f(a):
    b = a * 2
    while b.norm() < 1000:
        b = b * 2
    if b.sum() > 0:
        c = b
    else:
        c = 100 * b
    return c

In [79]:
a = torch.randn(size=(),requires_grad=True)

In [80]:
a

tensor(-1.8021, requires_grad=True)

In [81]:
d = f(a)

In [82]:
d.backward()

In [83]:
a.grad == d / a

tensor(True)