In [19]:
import torch
from d2l import torch as d2l

In [20]:
def corr2d_multi_in(X,K):
    return sum(d2l.corr2d(x,k) for x,k in zip(X,K))  # 好精简的代码

In [21]:
X = torch.tensor([[[0,1,2],[3,4,5],[6,7,8]],[[1,2,3],[4,5,6],[7,8,9]]])
K = torch.tensor([[[0,1],[2,3]],[[1,2],[3,4]]])

In [22]:
corr = corr2d_multi_in(X, K)

In [23]:
corr

tensor([[ 56.,  72.],
        [104., 120.]])

In [24]:
# 多通道输出四维张量
def corr2d_mulit_in_out(X,K):
    return torch.stack([corr2d_multi_in(X,k) for k in K],0)  # 这个业务逻辑怎么运作的

In [25]:
K = torch.stack((K,K+1,K+2),0)  # 看来好像是将张量拼接 按照一定的轴
K.shape

torch.Size([3, 2, 2, 2])

In [26]:
corr2d_mulit_in_out(X,K)

tensor([[[ 56.,  72.],
         [104., 120.]],

        [[ 76., 100.],
         [148., 172.]],

        [[ 96., 128.],
         [192., 224.]]])

In [27]:
'''
1x1的卷积核：将通道压缩，输入和输出相同宽度和高度
像神经层的线性运算
'''

'\n1x1的卷积核：将通道压缩，输入和输出相同宽度和高度\n像神经层的线性运算\n'

In [30]:
def corr2d_mulit_in_out_1x1(X,K):
    c_i,h,w = X.shape
    c_o = K.shape[0]
    X = X.reshape((c_i,h*w))
    K = K.reshape((c_o,c_i))
    Y = torch.matmul(K,X)
    return Y.reshape((c_o,h,w))  # 怎么就等价于corr2d_mulit_in_out

In [31]:
X = torch.normal(0,1,(3,3,3))
K = torch.normal(0,1,(2,3,1,1))

In [32]:
Y1 = corr2d_mulit_in_out_1x1(X,K)
Y2 = corr2d_mulit_in_out(X,K)
assert float(torch.abs(Y1-Y2).sum()<1e6)

In [35]:
K.shape

torch.Size([2, 3, 1, 1])

In [36]:
X.shape

torch.Size([3, 3, 3])

In [39]:
'''
多输入和多输出可以拓展模型
1x1相当于全连接层
用于调整通道数和模型复杂度
'''

'\n多输入和多输出可以拓展模型\n1x1相当于全连接层\n用于调整通道数和模型复杂度\n'

In [40]:
Y1 == Y2

tensor([[[True, True, True],
         [True, True, True],
         [True, True, True]],

        [[True, True, True],
         [True, True, True],
         [True, True, True]]])