In [25]:
# 汇聚层 在宽度或者高度上变换像素点并不会影响输出 意味着具有更高效的识别能力

In [26]:
import torch
from torch import nn
from d2l.torch import d2l

In [27]:
def pool2d(X,pool_size,mode='max'):  # 汇聚层
    p_h,p_w = pool_size
    Y = torch.zeros(X.shape[0]-p_h+1,X.shape[1]-p_w+1)
    for i in range(Y.shape[0]):
        for j in range(Y.shape[1]):
            if mode=='max':
                Y[i,j] = X[i:i+p_h,j:j+p_w].max()
            elif mode=='avg':
                Y[i,j] = X[i:i+p_h,j:j+p_w].mean()
    return Y

In [28]:
X = torch.tensor([[0.0,1.0,2.0],[3,4,5],[6,7,8]])
pool2d(X,(2,2))

tensor([[4., 5.],
        [7., 8.]])

In [29]:
pool2d(X,(2,2),mode='avg')

tensor([[2., 3.],
        [5., 6.]])

In [30]:
# 填充和步幅
X = torch.arange(16,dtype=torch.float32).reshape((1,1,4,4))
X

tensor([[[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.],
          [12., 13., 14., 15.]]]])

In [31]:
pool2d = nn.MaxPool2d(2)  #默认一致
pool2d(X)

tensor([[[[ 5.,  7.],
          [13., 15.]]]])

In [32]:
# 手动填充 虽然我也不知道有什么用
pool2d = nn.MaxPool2d(2,padding=1,stride=2)  # 池化层的padding参数是填充负无穷 stride步长
pool2d(X)

tensor([[[[ 0.,  2.,  3.],
          [ 8., 10., 11.],
          [12., 14., 15.]]]])

In [33]:
pool2d = nn.MaxPool2d((2,3),stride=(2,3),padding=(0,1))  # 不同高宽
pool2d(X)

tensor([[[[ 5.,  7.],
          [13., 15.]]]])

In [34]:
# 多通道
X = torch.cat((X,X+1),dim=1)

In [35]:
X

tensor([[[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.],
          [12., 13., 14., 15.]],

         [[ 1.,  2.,  3.,  4.],
          [ 5.,  6.,  7.,  8.],
          [ 9., 10., 11., 12.],
          [13., 14., 15., 16.]]]])

In [36]:
pool2d = nn.MaxPool2d(3,padding=1,stride=2)

In [37]:
pool2d(X)

tensor([[[[ 5.,  7.],
          [13., 15.]],

         [[ 6.,  8.],
          [14., 16.]]]])