In [23]:
import torch
from torch import nn
import torch.nn.functional as F
from torchinfo import summary

In [24]:
class CenteredLayer(nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, X):
        return X - X.mean()

In [25]:
layer = CenteredLayer()
M = layer(torch.FloatTensor([1, 2, 3, 4, 5]))
M.mean()

tensor(0.)

In [26]:
net = nn.Sequential(nn.Linear(8,128),CenteredLayer())

In [27]:
Y = net(torch.rand(4,8))
Y.mean()

tensor(1.8626e-09, grad_fn=<MeanBackward0>)

In [28]:
print(net)

Sequential(
  (0): Linear(in_features=8, out_features=128, bias=True)
  (1): CenteredLayer()
)


In [29]:
summary(net,input_size=(4,8))

Layer (type:depth-idx)                   Output Shape              Param #
Sequential                               [4, 128]                  --
├─Linear: 1-1                            [4, 128]                  1,152
├─CenteredLayer: 1-2                     [4, 128]                  --
Total params: 1,152
Trainable params: 1,152
Non-trainable params: 0
Total mult-adds (M): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.01

In [30]:
class MyLinear(nn.Module):
    def __init__(self,in_units,units):
        super().__init__()
        self.weight = nn.Parameter(torch.randn(in_units,units))
        self.bias = nn.Parameter(torch.randn(units))

    def forward(self, x):
        linear = torch.matmul(x,self.weight.data) + self.bias.data  # matmul矩阵相乘
        return F.relu(linear)


In [31]:
linear = MyLinear(5,3)

In [32]:
linear.weight

Parameter containing:
tensor([[-0.6374,  0.7397,  0.7767],
        [ 0.3096,  0.4503, -1.0699],
        [ 0.7086, -0.1803,  0.8380],
        [ 1.5385, -0.0885,  0.8259],
        [-0.5223,  0.7253, -0.3960]], requires_grad=True)

In [33]:
linear(torch.rand(2,5))

tensor([[0.8795, 2.8564, 1.7306],
        [1.9656, 2.8922, 1.9725]])

In [34]:
net = nn.Sequential(MyLinear(3,5),CenteredLayer(),MyLinear(5,3))
Y = net(torch.zeros(2,3))

In [35]:
print(Y)

tensor([[0.5455, 0.0000, 0.0000],
        [0.5455, 0.0000, 0.0000]])


In [36]:
print(net)

Sequential(
  (0): MyLinear()
  (1): CenteredLayer()
  (2): MyLinear()
)
