In [2]:
# 读写文件
import torch
from torch import nn
from torch.nn import functional as F

In [6]:
x = torch.arange(4)
torch.save(x, 'x-file')  # 信息写入内存

In [7]:
x2 = torch.load('x-file')  # 信息读取
x2

tensor([0, 1, 2, 3])

In [9]:
y = torch.zeros(4)
torch.save([x, y], 'y-file')

In [10]:
x3, y3 = torch.load('y-file')

In [11]:
x3, y3

(tensor([0, 1, 2, 3]), tensor([0., 0., 0., 0.]))

In [12]:
# 最鲜艳 字典
my_dict = {'x': x, 'y': y}
torch.save(my_dict, 'my-dict')

In [13]:
my_dict2 = torch.load('my-dict')
my_dict2

{'x': tensor([0, 1, 2, 3]), 'y': tensor([0., 0., 0., 0.])}

In [14]:
my_dict2['x']

tensor([0, 1, 2, 3])

In [16]:
# 加载模型数据
class MLP(nn.Module):
    def __init__(self):
        super().__init__()
        self.hidden = nn.Linear(20,256)
        self.output = nn.Linear(256,10)

    def forward(self, x):
        return self.output(F.relu(self.hidden(x)))

In [17]:
net = MLP()
X = torch.randn(size=(2,20))
Y = net(X)

In [18]:
torch.save(net.state_dict(), 'mlp.params')

In [19]:
clone = MLP()
clone.load_state_dict(torch.load('mlp.params'))
clone.eval()  # 执行

MLP(
  (hidden): Linear(in_features=20, out_features=256, bias=True)
  (output): Linear(in_features=256, out_features=10, bias=True)
)

In [20]:
Y_clone = clone(X)
Y_clone == Y

tensor([[True, True, True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True, True, True]])